# Generated by Django 3.2.16 on 2023-02-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('time', models.CharField(max_length=10)),
                ('t_id', models.CharField(max_length=100)),
                ('t_st_name', models.CharField(max_length=100)),
                ('t_ent_price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('proj_return', models.FloatField()),
                ('net_return', models.FloatField()),
                ('position_size', models.FloatField()),
                ('type_of_t', models.CharField(max_length=100)),
            ],
        ),
    ]
