# Generated by Django 3.2.16 on 2023-02-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_t_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=255)),
                ('dhanClientId', models.CharField(max_length=50)),
                ('availableBalance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sodLimit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collateralAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receiveableAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilizedAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('blockedPayoutAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('withdrawableBalance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
