# Generated by Django 3.2.16 on 2023-03-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_clientdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positional_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('time', models.CharField(max_length=100)),
                ('stock_name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('qty', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('side', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('productType', models.CharField(max_length=100)),
                ('limitPrice', models.BigIntegerField(blank=True, default=0, null=True)),
                ('stopPrice', models.BigIntegerField(blank=True, default=0, null=True)),
                ('validity', models.CharField(blank=True, default='DAY', max_length=100, null=True)),
                ('disclosedQty', models.BigIntegerField(blank=True, default=0, max_length=100, null=True)),
                ('stopLoss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('takeProfit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
