# Generated by Django 3.2.16 on 2023-03-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_positional_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fyer_user_all_positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_total', models.BigIntegerField()),
                ('total_investment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_current_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_pl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pnl_perc', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fyer_user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('fy_id', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
            ],
        ),
    ]
