# Generated by Django 3.2.16 on 2023-03-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_fyer_user_all_positions_fyer_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='positional_data',
            name='trade_executed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
