# Generated by Django 3.2.16 on 2023-03-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_positional_data_trade_executed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nifty_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('entry_time', models.CharField(max_length=10)),
                ('Nifty_entry', models.FloatField()),
                ('Nifty_exit', models.FloatField(blank=True)),
                ('exit_time', models.CharField(blank=True, max_length=10)),
                ('move', models.BigIntegerField(blank=True, null=True)),
                ('counter_nifty_data', models.CharField(blank=True, max_length=10, null=True)),
                ('call_put', models.CharField(blank=True, max_length=10, null=True)),
                ('Event_type', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
