# Generated by Django 3.2.16 on 2023-03-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_nifty_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vwap_Telegram_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('time', models.CharField(max_length=10)),
                ('Count', models.BigIntegerField()),
                ('Nifty_strike', models.FloatField()),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField()),
                ('type_of_option', models.CharField(max_length=10)),
                ('net_point_captured', models.FloatField()),
            ],
        ),
    ]
