# Generated by Django 3.2.16 on 2023-03-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230312_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vwap_telegram_data',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
