# Generated by Django 3.2.16 on 2023-03-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_vwap_telegram_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vwap_telegram_data',
            name='Count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vwap_telegram_data',
            name='Nifty_strike',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vwap_telegram_data',
            name='entry_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vwap_telegram_data',
            name='exit_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vwap_telegram_data',
            name='net_point_captured',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vwap_telegram_data',
            name='type_of_option',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
