# Generated by Django 3.2.16 on 2023-03-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20230312_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='DXY_RSI_60',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('time', models.CharField(max_length=20)),
                ('title', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
